set -ga terminal-overrides "default-terminal"
set-option -ga escape-time 10
set-option -ga focus-events on
set -gq allow-passthrough on
set -g visual-activity off

unbind C-Space
set-option -g prefix C-Space
bind C-Space send-prefix
set -g status-style 'bg=#333333 fg=#5eacd3'

bind r source-file ~/.config/tmux/tmux.conf
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

bind -r f run-shell "tmux neww tmux-session"
bind -r i run-shell "tmux neww cht.sh" 
